### PR TITLE
Refactor ramowka into hooks

### PR DESCRIPTION
**Pull request by julianuziemblo**
Change RamowkaList widget to use hooks instead of FutureBuilder widget

### CODE REVIEW

**Comment by korkuck** [comment]
Resolve conflicts and merge

**Review by korkuck — DISMISSED** [review]

**Review by korkuck — APPROVED** [review]

**Review by korkuck — APPROVED** [review]

**Review by korkuck — APPROVED** [review]

**Review by korkuck — DISMISSED** [review]

**Review by Kszesiek — APPROVED** [review]
Merge time

**Review by Kszesiek — DISMISSED** [review]
Approve!

**Review by Kszesiek — APPROVED** [review]
3rd times the charm

**Pull request closed without merging**
